# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Static Website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare NodeJS environment
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: zip -r Webwallet.zip build

    - name: Save the builded file
      uses: actions/upload-artifact@v3
      with:
        name: Webwallet.zip
        path: Webwallet.zip

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Download Static Website
      uses: actions/download-artifact@v3
      with:
        name: Webwallet.zip
        path: Webwallet.zip

    - name: Name files for Release
      run: mv Webwallet.zip Webwallet-${{ steps.vars.outputs.tag }}.zip

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: Webwallet ${{ steps.vars.outputs.tag }}
        body_path: release-notes.md
        files: Webwallet-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




    


  


  

